export const credentialSeedData = [
  {
    hostname: 'core-rtr-01',
    username: 'admin',
    password: 'C0r3R0ut3r!2024',
    enable_password: 'En@bl3S3cr3t99',
    snmp_community: 'corp-private-rw',
    ssh_key_fingerprint: 'SHA256:xKd3mN9pQ2vR8sT1uW4xY6zA',
  },
  {
    hostname: 'core-rtr-02',
    username: 'admin',
    password: 'C0r3R0ut3r!2024',
    enable_password: 'En@bl3S3cr3t99',
    snmp_community: 'corp-private-rw',
    ssh_key_fingerprint: 'SHA256:bL5mO0qP3wS6tU9vX2yB7cD',
  },
  {
    hostname: 'edge-rtr-01',
    username: 'netops',
    password: 'Junip3r#Edge01!',
    enable_password: '',
    snmp_community: 'edge-snmp-ro',
    ssh_key_fingerprint: 'SHA256:eF8nP1qR4sU7vX0yA3bC6dG',
  },
  {
    hostname: 'branch-rtr-01',
    username: 'admin',
    password: 'Br@nch2024NYC!',
    enable_password: 'Enabl3NYC#99',
    snmp_community: 'branch-ro',
    ssh_key_fingerprint: 'SHA256:hI1oQ4rS7tV0wY3zA6bD9eF',
  },
  {
    hostname: 'branch-rtr-02',
    username: 'admin',
    password: 'Br@nch2024LAX!',
    enable_password: 'Enabl3LAX#99',
    snmp_community: 'branch-ro',
    ssh_key_fingerprint: 'SHA256:kL4pT7uU0vW3xZ6aB9cE2fH',
  },
  {
    hostname: 'core-sw-01',
    username: 'admin',
    password: 'C0reSwitch!01',
    enable_password: 'SwEn@ble99',
    snmp_community: 'corp-private-rw',
    ssh_key_fingerprint: 'SHA256:mN7qU0vV3wX6yB9cD2eG5fI',
  },
  {
    hostname: 'core-sw-02',
    username: 'admin',
    password: 'C0reSwitch!02',
    enable_password: 'SwEn@ble99',
    snmp_community: 'corp-private-rw',
    ssh_key_fingerprint: 'SHA256:oP0rV3wW6xY9zA2bE5cH8dJ',
  },
  {
    hostname: 'dist-sw-01',
    username: 'netadmin',
    password: 'D1stSW!2024',
    enable_password: 'D1stEn@ble',
    snmp_community: 'dist-snmp-ro',
    ssh_key_fingerprint: 'SHA256:qR3sX6yY9zA2bC5dF8eI1jK',
  },
  {
    hostname: 'dist-sw-02',
    username: 'netadmin',
    password: 'D1stSW!2024',
    enable_password: 'D1stEn@ble',
    snmp_community: 'dist-snmp-ro',
    ssh_key_fingerprint: 'SHA256:sT6uZ9aA2bD5eF8gI1hL4jM',
  },
  {
    hostname: 'access-sw-01',
    username: 'admin',
    password: 'Acc3ss!Floor1',
    enable_password: 'Acc3ssEn@ble',
    snmp_community: 'access-ro',
    ssh_key_fingerprint: 'SHA256:uV9wB2xC5yD8eF1gH4iJ7kN',
  },
  {
    hostname: 'access-sw-02',
    username: 'admin',
    password: 'Acc3ss!Floor2',
    enable_password: 'Acc3ssEn@ble',
    snmp_community: 'access-ro',
    ssh_key_fingerprint: 'SHA256:wX2yD5zA8bC1dE4fG7hI0kO',
  },
  {
    hostname: 'mgmt-sw-01',
    username: 'manager',
    password: 'M@nag3ment!01',
    enable_password: 'MgmtEn@ble',
    snmp_community: 'mgmt-snmp-rw',
    ssh_key_fingerprint: 'SHA256:yZ5aF8bG1cH4dI7eJ0fK3lP',
  },
  {
    hostname: 'ap-floor1-01',
    username: 'ubnt',
    password: 'Ubnt!Floor1AP',
    enable_password: '',
    snmp_community: 'ubnt-snmp',
    ssh_key_fingerprint: 'SHA256:AA8cG1dH4eI7fJ0gK3hL6mQ',
  },
  {
    hostname: 'ap-floor2-01',
    username: 'ubnt',
    password: 'Ubnt!Floor2AP',
    enable_password: '',
    snmp_community: 'ubnt-snmp',
    ssh_key_fingerprint: 'SHA256:CC1eI4fJ7gK0hL3iM6jN9oR',
  },
  {
    hostname: 'ap-dc-01',
    username: 'Cisco',
    password: 'C1sc0!DCAP03',
    enable_password: '',
    snmp_community: 'cisco-snmp-ro',
    ssh_key_fingerprint: 'SHA256:EE4gK7hL0iM3jN6kO9lP2qS',
  },
]
