const now = new Date()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000)
const daysAgo = (d: number, h = 0) => new Date(now.getTime() - d * 86400000 - h * 3600000)

export const deviceLogSeedData = [
  // === dist-sw-02 (offline) — power failure sequence ===
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(8, 6),
    severity: 'warn' as const,
    facility: 'ENVM',
    message: 'Power supply 1 input voltage dropped below threshold: 210V (threshold: 220V)',
    raw_syslog: '<132>dist-sw-02 ENVM-4-WARN: Power supply 1 input voltage dropped below threshold',
  },
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(8, 5),
    severity: 'error' as const,
    facility: 'ENVM',
    message: 'Power supply 2 failure detected — output voltage 0V',
    raw_syslog: '<131>dist-sw-02 ENVM-3-ERR: Power supply 2 failure detected — output voltage 0V',
  },
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(8, 4),
    severity: 'critical' as const,
    facility: 'ENVM',
    message: 'Power supply 2 failure detected — redundancy lost',
    raw_syslog: '<130>dist-sw-02 ENVM-2-CRIT: Power supply 2 failure detected — redundancy lost',
  },
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(8, 3),
    severity: 'critical' as const,
    facility: 'ENVM',
    message: 'Power supply 2 failure detected — switching to PS1 only',
    raw_syslog: '<130>dist-sw-02 ENVM-2-CRIT: Power supply 2 failure detected — switching to PS1 only',
  },
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(8, 2),
    severity: 'critical' as const,
    facility: 'ENVM',
    message: 'CRITICAL: Both power supplies reporting fault condition — imminent shutdown',
    raw_syslog: '<130>dist-sw-02 ENVM-2-CRIT: CRITICAL: Both power supplies reporting fault condition',
  },
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(8, 1),
    severity: 'critical' as const,
    facility: 'SYS',
    message: 'System shutting down due to power failure — all interfaces going down',
    raw_syslog: '<130>dist-sw-02 SYS-2-CRIT: System shutting down due to power failure',
  },
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(8, 1),
    severity: 'critical' as const,
    facility: 'LINEPROTO',
    message: 'All 24 interfaces changed state to down',
    raw_syslog: '<130>dist-sw-02 LINEPROTO-5-UPDOWN: All interfaces changed state to down',
  },

  // === ap-dc-01 (degraded) — thermal/CPU issues ===
  {
    hostname: 'ap-dc-01',
    timestamp: daysAgo(5, 12),
    severity: 'warn' as const,
    facility: 'THERMAL',
    message: 'Temperature rising: 68°C (threshold warning: 65°C)',
    raw_syslog: '<132>ap-dc-01 THERMAL-4-WARN: Temperature rising: 68C',
  },
  {
    hostname: 'ap-dc-01',
    timestamp: daysAgo(5, 8),
    severity: 'error' as const,
    facility: 'CPU',
    message: 'CPU utilization 88% for 60s — check for runaway process',
    raw_syslog: '<131>ap-dc-01 CPU-3-ERR: CPU utilization 88% for 60s',
  },
  {
    hostname: 'ap-dc-01',
    timestamp: daysAgo(5, 6),
    severity: 'critical' as const,
    facility: 'THERMAL',
    message: 'Temperature threshold exceeded: 74°C (threshold: 70°C) — thermal throttling active',
    raw_syslog: '<130>ap-dc-01 THERMAL-2-CRIT: Temperature threshold exceeded: 74C (threshold: 70C)',
  },
  {
    hostname: 'ap-dc-01',
    timestamp: daysAgo(5, 4),
    severity: 'error' as const,
    facility: 'CPU',
    message: 'CPU utilization sustained above 85% — performance degraded',
    raw_syslog: '<131>ap-dc-01 CPU-3-ERR: CPU utilization sustained above 85%',
  },
  {
    hostname: 'ap-dc-01',
    timestamp: daysAgo(5, 2),
    severity: 'warn' as const,
    facility: 'DOT11',
    message: 'Radio 5GHz: beacon interval missed 3 consecutive times — clients may disconnect',
    raw_syslog: '<132>ap-dc-01 DOT11-4-WARN: Radio 5GHz beacon interval missed 3 consecutive times',
  },
  {
    hostname: 'ap-dc-01',
    timestamp: hoursAgo(6),
    severity: 'critical' as const,
    facility: 'THERMAL',
    message: 'Temperature threshold exceeded: 74°C — automatic shutdown may occur',
    raw_syslog: '<130>ap-dc-01 THERMAL-2-CRIT: Temperature threshold exceeded: 74C',
  },

  // === branch-rtr-01 (degraded) — failed logins + BGP + CPU ===
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(3, 14),
    severity: 'warn' as const,
    facility: 'SEC_LOGIN',
    message: "Login failed for user 'admin' from 192.168.50.100 — invalid password",
    raw_syslog: "<132>branch-rtr-01 SEC_LOGIN-4-WARN: Login failed for user 'admin' from 192.168.50.100",
  },
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(3, 13),
    severity: 'warn' as const,
    facility: 'SEC_LOGIN',
    message: "Login failed for user 'admin' from 192.168.50.100 — invalid password (attempt 2/5)",
    raw_syslog: "<132>branch-rtr-01 SEC_LOGIN-4-WARN: Login failed for user 'admin' from 192.168.50.100 attempt 2",
  },
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(3, 12),
    severity: 'warn' as const,
    facility: 'SEC_LOGIN',
    message: "Login failed for user 'admin' from 192.168.50.100 — invalid password (attempt 3/5)",
    raw_syslog: "<132>branch-rtr-01 SEC_LOGIN-4-WARN: Login failed for user 'admin' from 192.168.50.100 attempt 3",
  },
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(3, 10),
    severity: 'error' as const,
    facility: 'BGP',
    message: 'BGP session with 10.1.0.254 dropped — hold timer expired',
    raw_syslog: '<131>branch-rtr-01 BGP-3-ERR: BGP session with 10.1.0.254 dropped — hold timer expired',
  },
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(3, 8),
    severity: 'warn' as const,
    facility: 'CPU',
    message: 'CPU utilization 78% for 300s — possible routing loop or DoS condition',
    raw_syslog: '<132>branch-rtr-01 CPU-4-WARN: CPU utilization 78% for 300s',
  },
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(3, 6),
    severity: 'error' as const,
    facility: 'OSPF',
    message: 'OSPF neighbor 10.1.0.254 state changed from FULL to DOWN',
    raw_syslog: '<131>branch-rtr-01 OSPF-3-ERR: OSPF neighbor 10.1.0.254 state changed to DOWN',
  },
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(2, 18),
    severity: 'info' as const,
    facility: 'BGP',
    message: 'BGP session with 10.1.0.254 re-established — 42 prefixes received',
    raw_syslog: '<134>branch-rtr-01 BGP-5-INFO: BGP session with 10.1.0.254 re-established',
  },

  // === core-rtr-01 — normal operations ===
  {
    hostname: 'core-rtr-01',
    timestamp: daysAgo(1, 2),
    severity: 'info' as const,
    facility: 'OSPF',
    message: 'Neighbor 10.0.0.2 changed state to Full — FULL/DR',
    raw_syslog: '<134>core-rtr-01 OSPF-5-INFO: Neighbor 10.0.0.2 changed state to Full',
  },
  {
    hostname: 'core-rtr-01',
    timestamp: daysAgo(1, 1),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'Config backup completed successfully — 2048 bytes written to TFTP 10.0.5.1',
    raw_syslog: '<134>core-rtr-01 SYS-5-INFO: Config backup completed successfully',
  },
  {
    hostname: 'core-rtr-01',
    timestamp: daysAgo(7, 3),
    severity: 'warn' as const,
    facility: 'BGP',
    message: 'BGP prefix limit 90% reached for neighbor 10.0.0.2 (900/1000 prefixes)',
    raw_syslog: '<132>core-rtr-01 BGP-4-WARN: BGP prefix limit 90% reached for neighbor 10.0.0.2',
  },
  {
    hostname: 'core-rtr-01',
    timestamp: daysAgo(14, 6),
    severity: 'info' as const,
    facility: 'SEC_LOGIN',
    message: "SSH login successful for user 'admin' from 10.0.5.10",
    raw_syslog: "<134>core-rtr-01 SEC_LOGIN-5-INFO: SSH login successful for user 'admin' from 10.0.5.10",
  },
  {
    hostname: 'core-rtr-01',
    timestamp: daysAgo(20, 10),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet0/0/0: link type changed to full-duplex 1Gbps',
    raw_syslog: '<134>core-rtr-01 LINEPROTO-5-UPDOWN: GigabitEthernet0/0/0 changed to up',
  },

  // === core-rtr-02 — normal operations ===
  {
    hostname: 'core-rtr-02',
    timestamp: daysAgo(1, 2),
    severity: 'info' as const,
    facility: 'OSPF',
    message: 'Neighbor 10.0.0.1 changed state to Full — FULL/BDR',
    raw_syslog: '<134>core-rtr-02 OSPF-5-INFO: Neighbor 10.0.0.1 changed state to Full',
  },
  {
    hostname: 'core-rtr-02',
    timestamp: daysAgo(5, 4),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'Config backup completed successfully',
    raw_syslog: '<134>core-rtr-02 SYS-5-INFO: Config backup completed successfully',
  },
  {
    hostname: 'core-rtr-02',
    timestamp: daysAgo(10, 2),
    severity: 'info' as const,
    facility: 'SEC_LOGIN',
    message: "SSH login successful for user 'admin' from 10.0.5.10",
    raw_syslog: "<134>core-rtr-02 SEC_LOGIN-5-INFO: SSH login successful for user 'admin' from 10.0.5.10",
  },
  {
    hostname: 'core-rtr-02',
    timestamp: daysAgo(25, 8),
    severity: 'warn' as const,
    facility: 'INTERFACE',
    message: 'GigabitEthernet0/0/2 input error rate exceeded threshold: 0.02%',
    raw_syslog: '<132>core-rtr-02 INTERFACE-4-WARN: GigabitEthernet0/0/2 input error rate exceeded',
  },

  // === edge-rtr-01 — Juniper events ===
  {
    hostname: 'edge-rtr-01',
    timestamp: daysAgo(2, 3),
    severity: 'info' as const,
    facility: 'RPD',
    message: 'BGP peer 203.0.113.1 (External AS 65000) established — 125492 prefixes received',
    raw_syslog: '<134>edge-rtr-01 rpd[1234]: bgp_listen_accept: EBGP peer 203.0.113.1 established',
  },
  {
    hostname: 'edge-rtr-01',
    timestamp: daysAgo(12, 7),
    severity: 'warn' as const,
    facility: 'CHASSIS',
    message: 'FPC0 PIC0 minor alarm: SFP module temperature 68°C (warning threshold 65°C)',
    raw_syslog: '<132>edge-rtr-01 chassis[801]: FPC0 PIC0 minor alarm: SFP temperature 68C',
  },
  {
    hostname: 'edge-rtr-01',
    timestamp: daysAgo(18, 5),
    severity: 'info' as const,
    facility: 'UI',
    message: "Login: user 'netops' logged in from 10.0.5.10 on ssh",
    raw_syslog: "<134>edge-rtr-01 mgd[5678]: UI_LOGIN_EVENT: User 'netops' login, class 'super-user'",
  },
  {
    hostname: 'edge-rtr-01',
    timestamp: daysAgo(22, 9),
    severity: 'error' as const,
    facility: 'RPD',
    message: 'BGP peer 203.0.113.1 went down — received NOTIFICATION: hold timer expired',
    raw_syslog: '<131>edge-rtr-01 rpd[1234]: bgp_peer_down: EBGP peer 203.0.113.1 went down',
  },

  // === branch-rtr-02 — normal ===
  {
    hostname: 'branch-rtr-02',
    timestamp: daysAgo(1, 4),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'Config backup completed successfully',
    raw_syslog: '<134>branch-rtr-02 SYS-5-INFO: Config backup completed successfully',
  },
  {
    hostname: 'branch-rtr-02',
    timestamp: daysAgo(6, 9),
    severity: 'info' as const,
    facility: 'SEC_LOGIN',
    message: "SSH login successful for user 'admin' from 10.0.5.10",
    raw_syslog: "<134>branch-rtr-02 SEC_LOGIN-5-INFO: SSH login successful for user 'admin'",
  },
  {
    hostname: 'branch-rtr-02',
    timestamp: daysAgo(15, 11),
    severity: 'info' as const,
    facility: 'OSPF',
    message: 'OSPF neighbor 10.2.0.254 state changed to FULL',
    raw_syslog: '<134>branch-rtr-02 OSPF-5-INFO: Neighbor 10.2.0.254 changed state to Full',
  },
  {
    hostname: 'branch-rtr-02',
    timestamp: daysAgo(28, 3),
    severity: 'info' as const,
    facility: 'NTP',
    message: 'NTP: clock synchronized to 10.0.0.10, stratum 3',
    raw_syslog: '<134>branch-rtr-02 NTP-5-INFO: Clock synchronized to 10.0.0.10',
  },

  // === core-sw-01 — switch events ===
  {
    hostname: 'core-sw-01',
    timestamp: daysAgo(1, 3),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet1/0/1: link state changed to up',
    raw_syslog: '<134>core-sw-01 LINEPROTO-5-UPDOWN: GigabitEthernet1/0/1 changed to up',
  },
  {
    hostname: 'core-sw-01',
    timestamp: daysAgo(4, 6),
    severity: 'info' as const,
    facility: 'SPANTREE',
    message: 'VLAN0020: Topology change detected — root bridge re-elected',
    raw_syslog: '<134>core-sw-01 SPANTREE-5-INFO: VLAN0020 topology change notification',
  },
  {
    hostname: 'core-sw-01',
    timestamp: daysAgo(11, 2),
    severity: 'warn' as const,
    facility: 'MAC_LIMIT',
    message: 'MAC address table nearing limit: 14850/16000 entries',
    raw_syslog: '<132>core-sw-01 MAC_LIMIT-4-WARN: MAC table 92% full: 14850/16000',
  },
  {
    hostname: 'core-sw-01',
    timestamp: daysAgo(20, 8),
    severity: 'info' as const,
    facility: 'SEC_LOGIN',
    message: "SSH login successful for user 'admin' from 10.0.5.10",
    raw_syslog: "<134>core-sw-01 SEC_LOGIN-5-INFO: SSH login successful for user 'admin'",
  },
  {
    hostname: 'core-sw-01',
    timestamp: daysAgo(29, 5),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'SNMP trap sent to 10.0.5.1: linkUp GigabitEthernet1/0/3',
    raw_syslog: '<134>core-sw-01 SYS-5-INFO: SNMP trap linkUp sent for Gi1/0/3',
  },

  // === core-sw-02 — switch events ===
  {
    hostname: 'core-sw-02',
    timestamp: daysAgo(2, 4),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet1/0/48: link state changed to up',
    raw_syslog: '<134>core-sw-02 LINEPROTO-5-UPDOWN: GigabitEthernet1/0/48 changed to up',
  },
  {
    hostname: 'core-sw-02',
    timestamp: daysAgo(9, 3),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'Spanning tree topology stabilized on all VLANs',
    raw_syslog: '<134>core-sw-02 SYS-5-INFO: STP topology stabilized',
  },
  {
    hostname: 'core-sw-02',
    timestamp: daysAgo(17, 7),
    severity: 'warn' as const,
    facility: 'INTERFACE',
    message: 'GigabitEthernet1/0/12: input CRC errors exceeded 100/min — check cable',
    raw_syslog: '<132>core-sw-02 INTERFACE-4-WARN: Gi1/0/12 CRC error rate exceeded threshold',
  },
  {
    hostname: 'core-sw-02',
    timestamp: daysAgo(26, 1),
    severity: 'info' as const,
    facility: 'SEC_LOGIN',
    message: "SSH login successful for user 'admin' from 10.0.5.10",
    raw_syslog: "<134>core-sw-02 SEC_LOGIN-5-INFO: SSH login successful for user 'admin'",
  },

  // === dist-sw-01 — distribution switch ===
  {
    hostname: 'dist-sw-01',
    timestamp: daysAgo(3, 5),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'Config backup completed — 1267 bytes',
    raw_syslog: '<134>dist-sw-01 SYS-5-INFO: Config backup completed',
  },
  {
    hostname: 'dist-sw-01',
    timestamp: daysAgo(8, 7),
    severity: 'warn' as const,
    facility: 'ENVM',
    message: 'Fan tray 1 speed reduced — verify airflow is not obstructed',
    raw_syslog: '<132>dist-sw-01 ENVM-4-WARN: Fan tray 1 speed reduction detected',
  },
  {
    hostname: 'dist-sw-01',
    timestamp: daysAgo(13, 4),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet1/0/22: link state changed to up',
    raw_syslog: '<134>dist-sw-01 LINEPROTO-5-UPDOWN: GigabitEthernet1/0/22 changed to up',
  },
  {
    hostname: 'dist-sw-01',
    timestamp: daysAgo(21, 6),
    severity: 'info' as const,
    facility: 'SPANTREE',
    message: 'RSTP port GigabitEthernet1/0/1 transitioned to forwarding state',
    raw_syslog: '<134>dist-sw-01 SPANTREE-5-INFO: GigabitEthernet1/0/1 transitioned to forwarding',
  },

  // === access-sw-01 — floor 1 access layer ===
  {
    hostname: 'access-sw-01',
    timestamp: hoursAgo(3),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet0/37: link state changed to up — new device connected',
    raw_syslog: '<134>access-sw-01 LINEPROTO-5-UPDOWN: GigabitEthernet0/37 changed to up',
  },
  {
    hostname: 'access-sw-01',
    timestamp: daysAgo(4, 8),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet0/22: link state changed to down',
    raw_syslog: '<134>access-sw-01 LINEPROTO-5-UPDOWN: GigabitEthernet0/22 changed to down',
  },
  {
    hostname: 'access-sw-01',
    timestamp: daysAgo(9, 11),
    severity: 'warn' as const,
    facility: 'DHCP_SNOOPING',
    message: 'DHCP snooping: unexpected DHCP server reply on untrusted port Gi0/14 — source 192.168.30.200',
    raw_syslog: '<132>access-sw-01 DHCP_SNOOPING-4-WARN: DHCP server reply on untrusted port Gi0/14',
  },
  {
    hostname: 'access-sw-01',
    timestamp: daysAgo(16, 3),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'Config backup completed successfully',
    raw_syslog: '<134>access-sw-01 SYS-5-INFO: Config backup completed',
  },
  {
    hostname: 'access-sw-01',
    timestamp: daysAgo(24, 9),
    severity: 'info' as const,
    facility: 'SPANTREE',
    message: 'PortFast BPDU guard violation detected on GigabitEthernet0/8 — port disabled',
    raw_syslog: '<134>access-sw-01 SPANTREE-5-BPDUGUARD: PortFast BPDU guard violation on Gi0/8',
  },

  // === access-sw-02 — floor 2 access layer ===
  {
    hostname: 'access-sw-02',
    timestamp: hoursAgo(1),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet0/15: link state changed to up',
    raw_syslog: '<134>access-sw-02 LINEPROTO-5-UPDOWN: GigabitEthernet0/15 changed to up',
  },
  {
    hostname: 'access-sw-02',
    timestamp: daysAgo(5, 7),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet0/31: link state changed to down',
    raw_syslog: '<134>access-sw-02 LINEPROTO-5-UPDOWN: GigabitEthernet0/31 changed to down',
  },
  {
    hostname: 'access-sw-02',
    timestamp: daysAgo(11, 2),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'NTP synchronization achieved with 10.0.0.10',
    raw_syslog: '<134>access-sw-02 SYS-5-INFO: NTP sync achieved with 10.0.0.10',
  },
  {
    hostname: 'access-sw-02',
    timestamp: daysAgo(19, 4),
    severity: 'warn' as const,
    facility: 'PORT_SECURITY',
    message: 'Port security violation on GigabitEthernet0/7 — unknown MAC AA:BB:CC:DD:EE:FF',
    raw_syslog: '<132>access-sw-02 PORT_SECURITY-4-WARN: Port security violation on Gi0/7',
  },
  {
    hostname: 'access-sw-02',
    timestamp: daysAgo(27, 6),
    severity: 'info' as const,
    facility: 'SEC_LOGIN',
    message: "SSH login successful for user 'admin' from 10.0.5.10",
    raw_syslog: "<134>access-sw-02 SEC_LOGIN-5-INFO: SSH login successful for user 'admin'",
  },

  // === mgmt-sw-01 — management switch ===
  {
    hostname: 'mgmt-sw-01',
    timestamp: daysAgo(7, 2),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'Config backup completed',
    raw_syslog: '<134>mgmt-sw-01 SYS-5-INFO: Config backup completed',
  },
  {
    hostname: 'mgmt-sw-01',
    timestamp: daysAgo(14, 5),
    severity: 'info' as const,
    facility: 'INTERFACE',
    message: 'Port 5 link up at 1000Mbps full-duplex',
    raw_syslog: '<134>mgmt-sw-01 interface: Port 5 link up at 1000Mbps',
  },
  {
    hostname: 'mgmt-sw-01',
    timestamp: daysAgo(20, 8),
    severity: 'info' as const,
    facility: 'MGMT',
    message: 'SNMP trap forwarded to collector 10.0.5.1: coldStart',
    raw_syslog: '<134>mgmt-sw-01 MGMT-5-INFO: SNMP coldStart trap sent to 10.0.5.1',
  },
  {
    hostname: 'mgmt-sw-01',
    timestamp: daysAgo(23, 3),
    severity: 'warn' as const,
    facility: 'AUTH',
    message: 'Authentication failure for user manager from 10.0.5.20',
    raw_syslog: '<132>mgmt-sw-01 AUTH-4-WARN: Authentication failure for user manager from 10.0.5.20',
  },

  // === ap-floor1-01 — UniFi AP events ===
  {
    hostname: 'ap-floor1-01',
    timestamp: hoursAgo(8),
    severity: 'info' as const,
    facility: 'WIRELESS',
    message: 'Client AA:11:22:33:44:55 associated to SSID CorpNet-5G on radio 5GHz',
    raw_syslog: '<134>ap-floor1-01 wireless: Client associated to CorpNet-5G',
  },
  {
    hostname: 'ap-floor1-01',
    timestamp: daysAgo(2, 14),
    severity: 'info' as const,
    facility: 'WIRELESS',
    message: 'Radio 5GHz: DFS channel change 100 → 36 due to radar detection',
    raw_syslog: '<134>ap-floor1-01 wireless: DFS radar detected, channel change 100 -> 36',
  },
  {
    hostname: 'ap-floor1-01',
    timestamp: daysAgo(6, 9),
    severity: 'info' as const,
    facility: 'UPGRADE',
    message: 'Firmware upgrade completed: 6.5.27.0 → 6.5.28.1',
    raw_syslog: '<134>ap-floor1-01 upgrade: Firmware upgraded to 6.5.28.1',
  },
  {
    hostname: 'ap-floor1-01',
    timestamp: daysAgo(10, 16),
    severity: 'warn' as const,
    facility: 'WIRELESS',
    message: 'High interference detected on 2.4GHz band — SNR dropped to 12dB',
    raw_syslog: '<132>ap-floor1-01 wireless: High interference on 2.4GHz, SNR 12dB',
  },
  {
    hostname: 'ap-floor1-01',
    timestamp: daysAgo(18, 7),
    severity: 'info' as const,
    facility: 'WIRELESS',
    message: 'Client roaming event: BB:22:33:44:55:66 roamed from ap-floor2-01',
    raw_syslog: '<134>ap-floor1-01 wireless: Client roaming from ap-floor2-01',
  },

  // === ap-floor2-01 — UniFi AP events ===
  {
    hostname: 'ap-floor2-01',
    timestamp: hoursAgo(5),
    severity: 'info' as const,
    facility: 'WIRELESS',
    message: 'Client CC:33:44:55:66:77 associated to SSID CorpNet on radio 2.4GHz',
    raw_syslog: '<134>ap-floor2-01 wireless: Client associated to CorpNet 2.4GHz',
  },
  {
    hostname: 'ap-floor2-01',
    timestamp: daysAgo(3, 11),
    severity: 'info' as const,
    facility: 'UPGRADE',
    message: 'Firmware upgrade completed: 6.5.27.0 → 6.5.28.1',
    raw_syslog: '<134>ap-floor2-01 upgrade: Firmware upgraded to 6.5.28.1',
  },
  {
    hostname: 'ap-floor2-01',
    timestamp: daysAgo(8, 4),
    severity: 'info' as const,
    facility: 'WIRELESS',
    message: '48 active clients on 5GHz radio',
    raw_syslog: '<134>ap-floor2-01 wireless: 48 active clients on 5GHz',
  },
  {
    hostname: 'ap-floor2-01',
    timestamp: daysAgo(15, 13),
    severity: 'warn' as const,
    facility: 'WIRELESS',
    message: 'Maximum client limit approaching: 95/100 clients associated',
    raw_syslog: '<132>ap-floor2-01 wireless: Client limit 95/100 — approaching maximum',
  },

  // === Additional mixed events to reach 120 total ===
  {
    hostname: 'core-rtr-01',
    timestamp: daysAgo(3, 1),
    severity: 'info' as const,
    facility: 'NTP',
    message: 'NTP clock synchronized to 10.0.0.10, offset 0.003s',
    raw_syslog: '<134>core-rtr-01 NTP-5-INFO: Clock synchronized, offset 0.003s',
  },
  {
    hostname: 'core-rtr-02',
    timestamp: daysAgo(4, 2),
    severity: 'info' as const,
    facility: 'SNMP',
    message: 'SNMP trap sent to 10.0.5.1: ifOperStatus GigabitEthernet0/0/1 up',
    raw_syslog: '<134>core-rtr-02 SNMP-5-INFO: SNMP trap ifOperStatus sent',
  },
  {
    hostname: 'dist-sw-01',
    timestamp: daysAgo(18, 3),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet1/0/5: link state changed to up',
    raw_syslog: '<134>dist-sw-01 LINEPROTO-5-UPDOWN: GigabitEthernet1/0/5 up',
  },
  {
    hostname: 'access-sw-01',
    timestamp: daysAgo(7, 12),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet0/44: link state changed to up',
    raw_syslog: '<134>access-sw-01 LINEPROTO-5-UPDOWN: GigabitEthernet0/44 up',
  },
  {
    hostname: 'access-sw-02',
    timestamp: daysAgo(3, 6),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet0/28: link state changed to up',
    raw_syslog: '<134>access-sw-02 LINEPROTO-5-UPDOWN: GigabitEthernet0/28 up',
  },
  {
    hostname: 'mgmt-sw-01',
    timestamp: daysAgo(10, 9),
    severity: 'info' as const,
    facility: 'INTERFACE',
    message: 'Port 12 link up at 100Mbps full-duplex',
    raw_syslog: '<134>mgmt-sw-01 interface: Port 12 link up at 100Mbps',
  },
  {
    hostname: 'edge-rtr-01',
    timestamp: daysAgo(3, 6),
    severity: 'info' as const,
    facility: 'KERNEL',
    message: 'Routing table updated: 498231 IPv4 routes active',
    raw_syslog: '<134>edge-rtr-01 kernel: Routing table updated: 498231 IPv4 routes',
  },
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(1, 3),
    severity: 'info' as const,
    facility: 'OSPF',
    message: 'OSPF neighbor 10.1.0.254 state changed to FULL',
    raw_syslog: '<134>branch-rtr-01 OSPF-5-INFO: Neighbor 10.1.0.254 changed state to Full',
  },
  {
    hostname: 'branch-rtr-02',
    timestamp: daysAgo(4, 7),
    severity: 'info' as const,
    facility: 'SEC_LOGIN',
    message: "SSH login successful for user 'admin' from 10.0.5.10",
    raw_syslog: "<134>branch-rtr-02 SEC_LOGIN-5-INFO: SSH login successful",
  },
  {
    hostname: 'core-sw-01',
    timestamp: daysAgo(6, 5),
    severity: 'info' as const,
    facility: 'SNMP',
    message: 'SNMP poll from 10.0.5.1 — 847 OIDs queried',
    raw_syslog: '<134>core-sw-01 SNMP-5-INFO: SNMP poll from 10.0.5.1',
  },
  {
    hostname: 'core-sw-02',
    timestamp: daysAgo(7, 3),
    severity: 'warn' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet1/0/36: flapping detected — 5 state changes in 60s',
    raw_syslog: '<132>core-sw-02 LINEPROTO-4-WARN: GigabitEthernet1/0/36 link flapping',
  },
  {
    hostname: 'ap-dc-01',
    timestamp: hoursAgo(2),
    severity: 'warn' as const,
    facility: 'CPU',
    message: 'CPU utilization still elevated at 82% — system unstable',
    raw_syslog: '<132>ap-dc-01 CPU-4-WARN: CPU utilization 82% — system unstable',
  },
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(30, 5),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'Config backup completed — 987 bytes',
    raw_syslog: '<134>dist-sw-02 SYS-5-INFO: Config backup completed',
  },
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(25, 8),
    severity: 'info' as const,
    facility: 'LINEPROTO',
    message: 'GigabitEthernet1/0/1: link state changed to up — UPLINK active',
    raw_syslog: '<134>dist-sw-02 LINEPROTO-5-UPDOWN: GigabitEthernet1/0/1 changed to up',
  },
  {
    hostname: 'core-rtr-01',
    timestamp: daysAgo(6, 4),
    severity: 'info' as const,
    facility: 'SEC_LOGIN',
    message: "SSH login successful for user 'admin' from 10.0.5.15",
    raw_syslog: "<134>core-rtr-01 SEC_LOGIN-5-INFO: SSH login for user 'admin' from 10.0.5.15",
  },
  {
    hostname: 'core-rtr-02',
    timestamp: daysAgo(8, 6),
    severity: 'warn' as const,
    facility: 'INTERFACE',
    message: 'GigabitEthernet0/0/1: output queue drops exceeded 1000/min',
    raw_syslog: '<132>core-rtr-02 INTERFACE-4-WARN: Gi0/0/1 output queue drops exceeded',
  },
  {
    hostname: 'edge-rtr-01',
    timestamp: daysAgo(25, 2),
    severity: 'info' as const,
    facility: 'COMMIT',
    message: 'Configuration committed by user netops — 3 changes applied',
    raw_syslog: '<134>edge-rtr-01 mgd[5678]: UI_COMMIT: User netops committed 3 changes',
  },
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(10, 14),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'Config backup completed — pre-change backup',
    raw_syslog: '<134>branch-rtr-01 SYS-5-INFO: Config backup completed (pre-change)',
  },
  {
    hostname: 'ap-floor1-01',
    timestamp: daysAgo(22, 4),
    severity: 'info' as const,
    facility: 'WIRELESS',
    message: '36 active clients: 8 on 2.4GHz, 28 on 5GHz',
    raw_syslog: '<134>ap-floor1-01 wireless: 36 active clients',
  },
  {
    hostname: 'ap-floor2-01',
    timestamp: daysAgo(24, 6),
    severity: 'info' as const,
    facility: 'WIRELESS',
    message: 'Band steering event: 12 clients moved from 2.4GHz to 5GHz',
    raw_syslog: '<134>ap-floor2-01 wireless: Band steering moved 12 clients to 5GHz',
  },
  {
    hostname: 'mgmt-sw-01',
    timestamp: daysAgo(28, 11),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'System uptime: 166 days, 14 hours, 23 minutes',
    raw_syslog: '<134>mgmt-sw-01 SYS-5-INFO: Uptime 166d 14h 23m',
  },
  {
    hostname: 'dist-sw-01',
    timestamp: daysAgo(25, 7),
    severity: 'info' as const,
    facility: 'SNMP',
    message: 'SNMP poll from 10.0.5.1 — 512 OIDs queried',
    raw_syslog: '<134>dist-sw-01 SNMP-5-INFO: SNMP poll from 10.0.5.1',
  },
  {
    hostname: 'access-sw-01',
    timestamp: daysAgo(29, 2),
    severity: 'info' as const,
    facility: 'SEC_LOGIN',
    message: "SSH login successful for user 'admin' from 10.0.5.10",
    raw_syslog: "<134>access-sw-01 SEC_LOGIN-5-INFO: SSH login for user 'admin'",
  },
  {
    hostname: 'access-sw-02',
    timestamp: daysAgo(28, 4),
    severity: 'info' as const,
    facility: 'NTP',
    message: 'NTP synchronized to 10.0.0.10',
    raw_syslog: '<134>access-sw-02 NTP-5-INFO: NTP synchronized',
  },
  {
    hostname: 'core-sw-01',
    timestamp: daysAgo(28, 9),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'HSRP state changed to Active on VLAN 20',
    raw_syslog: '<134>core-sw-01 SYS-5-INFO: HSRP active on VLAN 20',
  },
  {
    hostname: 'core-sw-02',
    timestamp: daysAgo(28, 9),
    severity: 'info' as const,
    facility: 'SYS',
    message: 'HSRP state changed to Standby on VLAN 20',
    raw_syslog: '<134>core-sw-02 SYS-5-INFO: HSRP standby on VLAN 20',
  },
  {
    hostname: 'core-rtr-01',
    timestamp: daysAgo(29, 6),
    severity: 'info' as const,
    facility: 'IPSEC',
    message: 'IPSec tunnel to 10.2.0.1 (branch-rtr-02) re-keyed successfully',
    raw_syslog: '<134>core-rtr-01 IPSEC-5-INFO: IPSec tunnel re-keyed to 10.2.0.1',
  },
  {
    hostname: 'branch-rtr-01',
    timestamp: daysAgo(15, 9),
    severity: 'warn' as const,
    facility: 'MEMORY',
    message: 'Free memory dropped below 15%: 92MB free of 512MB',
    raw_syslog: '<132>branch-rtr-01 MEMORY-4-WARN: Free memory 15%: 92MB/512MB',
  },
  {
    hostname: 'ap-dc-01',
    timestamp: daysAgo(3, 10),
    severity: 'error' as const,
    facility: 'THERMAL',
    message: 'Cooling fan speed critical — possible fan failure detected',
    raw_syslog: '<131>ap-dc-01 THERMAL-3-ERR: Cooling fan speed critical',
  },
  {
    hostname: 'dist-sw-02',
    timestamp: daysAgo(9, 3),
    severity: 'warn' as const,
    facility: 'ENVM',
    message: 'Power supply 1 output voltage fluctuating — 11.8V-12.2V (nominal 12.0V)',
    raw_syslog: '<132>dist-sw-02 ENVM-4-WARN: PS1 output voltage fluctuating',
  },
  {
    hostname: 'edge-rtr-01',
    timestamp: daysAgo(7, 15),
    severity: 'info' as const,
    facility: 'ROUTING',
    message: 'Route table optimization complete — 2847 prefixes aggregated',
    raw_syslog: '<134>edge-rtr-01 routing: Route optimization complete, 2847 prefixes aggregated',
  },
  {
    hostname: 'core-rtr-01',
    timestamp: daysAgo(11, 8),
    severity: 'warn' as const,
    facility: 'QOS',
    message: 'QoS policy: DSCP remarking queue 78% full on GigabitEthernet0/0/0',
    raw_syslog: '<132>core-rtr-01 QOS-4-WARN: DSCP remarking queue 78% full',
  },
]
