export const deviceSeedData = [
  {
    hostname: 'core-rtr-01',
    type: 'router' as const,
    ip_address: '10.0.0.1',
    mac_address: 'AA:BB:CC:00:00:01',
    location: 'DC-A / Core',
    rack_unit: 'Rack 1 U1',
    firmware_version: '17.6.1a',
    serial_number: 'SN-RTR-001',
    status: 'online' as const,
    vendor: 'Cisco',
    model: 'ASR1001-X',
  },
  {
    hostname: 'core-rtr-02',
    type: 'router' as const,
    ip_address: '10.0.0.2',
    mac_address: 'AA:BB:CC:00:00:02',
    location: 'DC-A / Core',
    rack_unit: 'Rack 1 U2',
    firmware_version: '17.6.1a',
    serial_number: 'SN-RTR-002',
    status: 'online' as const,
    vendor: 'Cisco',
    model: 'ASR1001-X',
  },
  {
    hostname: 'edge-rtr-01',
    type: 'router' as const,
    ip_address: '10.0.1.1',
    mac_address: 'AA:BB:CC:00:01:01',
    location: 'DC-A / Edge',
    rack_unit: 'Rack 2 U1',
    firmware_version: '21.4R3-S5',
    serial_number: 'SN-RTR-003',
    status: 'online' as const,
    vendor: 'Juniper',
    model: 'MX204',
  },
  {
    hostname: 'branch-rtr-01',
    type: 'router' as const,
    ip_address: '10.1.0.1',
    mac_address: 'AA:BB:CC:00:02:01',
    location: 'Branch-NYC / Rack 1 U1',
    rack_unit: 'Rack 1 U1',
    firmware_version: '16.9.8',
    serial_number: 'SN-RTR-004',
    status: 'degraded' as const,
    vendor: 'Cisco',
    model: 'ISR4331',
  },
  {
    hostname: 'branch-rtr-02',
    type: 'router' as const,
    ip_address: '10.2.0.1',
    mac_address: 'AA:BB:CC:00:03:01',
    location: 'Branch-LAX / Rack 1 U1',
    rack_unit: 'Rack 1 U1',
    firmware_version: '16.9.8',
    serial_number: 'SN-RTR-005',
    status: 'online' as const,
    vendor: 'Cisco',
    model: 'ISR4331',
  },
  {
    hostname: 'core-sw-01',
    type: 'switch' as const,
    ip_address: '10.0.2.1',
    mac_address: 'AA:BB:CC:00:04:01',
    location: 'DC-A / Core',
    rack_unit: 'Rack 3 U1',
    firmware_version: '17.6.2',
    serial_number: 'SN-SW-001',
    status: 'online' as const,
    vendor: 'Cisco',
    model: 'Catalyst 9500',
  },
  {
    hostname: 'core-sw-02',
    type: 'switch' as const,
    ip_address: '10.0.2.2',
    mac_address: 'AA:BB:CC:00:04:02',
    location: 'DC-A / Core',
    rack_unit: 'Rack 3 U2',
    firmware_version: '17.6.2',
    serial_number: 'SN-SW-002',
    status: 'online' as const,
    vendor: 'Cisco',
    model: 'Catalyst 9500',
  },
  {
    hostname: 'dist-sw-01',
    type: 'switch' as const,
    ip_address: '10.0.3.1',
    mac_address: 'AA:BB:CC:00:05:01',
    location: 'DC-A / Distribution',
    rack_unit: 'Rack 4 U1',
    firmware_version: '16.12.8',
    serial_number: 'SN-SW-003',
    status: 'online' as const,
    vendor: 'Cisco',
    model: 'Catalyst 9300',
  },
  {
    hostname: 'dist-sw-02',
    type: 'switch' as const,
    ip_address: '10.0.3.2',
    mac_address: 'AA:BB:CC:00:05:02',
    location: 'DC-A / Distribution',
    rack_unit: 'Rack 4 U2',
    firmware_version: '16.12.8',
    serial_number: 'SN-SW-004',
    status: 'offline' as const,
    vendor: 'Cisco',
    model: 'Catalyst 9300',
  },
  {
    hostname: 'access-sw-01',
    type: 'switch' as const,
    ip_address: '10.0.4.1',
    mac_address: 'AA:BB:CC:00:06:01',
    location: 'Floor-1 / Rack 5 U1',
    rack_unit: 'Rack 5 U1',
    firmware_version: '15.2.7',
    serial_number: 'SN-SW-005',
    status: 'online' as const,
    vendor: 'Cisco',
    model: 'Catalyst 2960X',
  },
  {
    hostname: 'access-sw-02',
    type: 'switch' as const,
    ip_address: '10.0.4.2',
    mac_address: 'AA:BB:CC:00:06:02',
    location: 'Floor-2 / Rack 6 U1',
    rack_unit: 'Rack 6 U1',
    firmware_version: '15.2.7',
    serial_number: 'SN-SW-006',
    status: 'online' as const,
    vendor: 'Cisco',
    model: 'Catalyst 2960X',
  },
  {
    hostname: 'mgmt-sw-01',
    type: 'switch' as const,
    ip_address: '10.0.5.1',
    mac_address: 'AA:BB:CC:00:07:01',
    location: 'DC-A / Management',
    rack_unit: 'Rack 7 U1',
    firmware_version: 'K.15.16.0008',
    serial_number: 'SN-SW-007',
    status: 'online' as const,
    vendor: 'HP',
    model: 'ProCurve 2920',
  },
  {
    hostname: 'ap-floor1-01',
    type: 'access_point' as const,
    ip_address: '10.0.6.1',
    mac_address: 'AA:BB:CC:00:08:01',
    location: 'Floor-1 / Ceiling Sector A',
    rack_unit: 'N/A',
    firmware_version: '6.5.28.1',
    serial_number: 'SN-AP-001',
    status: 'online' as const,
    vendor: 'Ubiquiti',
    model: 'UniFi U6-Pro',
  },
  {
    hostname: 'ap-floor2-01',
    type: 'access_point' as const,
    ip_address: '10.0.6.2',
    mac_address: 'AA:BB:CC:00:08:02',
    location: 'Floor-2 / Ceiling Sector B',
    rack_unit: 'N/A',
    firmware_version: '6.5.28.1',
    serial_number: 'SN-AP-002',
    status: 'online' as const,
    vendor: 'Ubiquiti',
    model: 'UniFi U6-LR',
  },
  {
    hostname: 'ap-dc-01',
    type: 'access_point' as const,
    ip_address: '10.0.6.3',
    mac_address: 'AA:BB:CC:00:08:03',
    location: 'DC-A / Ceiling',
    rack_unit: 'N/A',
    firmware_version: '8.10.150.0',
    serial_number: 'SN-AP-003',
    status: 'degraded' as const,
    vendor: 'Cisco',
    model: 'Aironet 2802i',
  },
]
